Repository usamasaleem1/SOEN341, pull requests merged in 2021-10, with the labels that each got.

#23 Created a register page #11
  backend/app/Http/Controllers/AuthController.php
  backend/resources/views/index.blade.php
  backend/resources/views/layouts/main.blade.php
  backend/resources/views/register.blade.php
  backend/resources/views/welcome.blade.php
  backend/routes/web.php
Labels: backend, frontend

#46 Added a very basic Syntax highlighting for code #45
  backend/app/Models/Question.php
  backend/app/Models/Tag.php
  backend/database/migrations/2021_10_08_034616_create_tags_table.php
  backend/public/js/codeFormatters.js
  backend/resources/views/home.blade.php
Labels: subtask

#50 Adding tags and syntax highlight #49
  backend/app/Http/Controllers/QuestionController.php
  backend/database/migrations/2021_10_08_202708_adding_tags_t_o_d_b.php
  backend/public/js/codeFormatters.js
  backend/resources/views/home.blade.php
  backend/resources/views/post.blade.php
Labels: story, subtask

#54 Fixed lots of bugs (mainly incorrect ordering) #53
  backend/app/Http/Controllers/AuthController.php
  backend/app/Http/Controllers/QuestionController.php
  backend/resources/views/post.blade.php
  backend/routes/web.php
Labels: bug

#56 Fixed gradient bug related to #45
  backend/public/css/style.css
  backend/resources/views/layouts/withHeader.blade.php
Labels: bug
